package com.zanon.android.adb.android

object Settings {
    const val DEFAULT_OVERRIDEABLE_BY_RESTORE = false
    const val ACTION_SETTINGS = "android.settings.SETTINGS"
    const val ACTION_APN_SETTINGS = "android.settings.APN_SETTINGS"
    const val ACTION_LOCATION_SOURCE_SETTINGS = "android.settings.LOCATION_SOURCE_SETTINGS"

    const val ACTION_LOCATION_CONTROLLER_EXTRA_PACKAGE_SETTINGS =
        "android.settings.LOCATION_CONTROLLER_EXTRA_PACKAGE_SETTINGS"
    const val ACTION_LOCATION_SCANNING_SETTINGS = "android.settings.LOCATION_SCANNING_SETTINGS"
    const val ACTION_USER_SETTINGS = "android.settings.USER_SETTINGS"
    const val ACTION_WIRELESS_SETTINGS = "android.settings.WIRELESS_SETTINGS"

    const val ACTION_TETHER_PROVISIONING_UI = "android.settings.TETHER_PROVISIONING_UI"
    const val ACTION_AIRPLANE_MODE_SETTINGS = "android.settings.AIRPLANE_MODE_SETTINGS"
    const val ACTION_MOBILE_DATA_USAGE = "android.settings.MOBILE_DATA_USAGE"
    const val EXTRA_NETWORK_TEMPLATE = "network_template"
    const val KEY_CONFIG_SET_RETURN = "config_set_return"
    const val EXTRA_SUB_ID = "android.provider.extra.SUB_ID"
    const val ACTION_VOICE_CONTROL_AIRPLANE_MODE = "android.settings.VOICE_CONTROL_AIRPLANE_MODE"
    const val ACTION_ACCESSIBILITY_SETTINGS = "android.settings.ACCESSIBILITY_SETTINGS"

    const val ACTION_ACCESSIBILITY_DETAILS_SETTINGS = "android.settings.ACCESSIBILITY_DETAILS_SETTINGS"
    const val ACTION_USAGE_ACCESS_SETTINGS = "android.settings.USAGE_ACCESS_SETTINGS"
    const val INTENT_CATEGORY_USAGE_ACCESS_CONFIG = "android.intent.category.USAGE_ACCESS_CONFIG"
    const val METADATA_USAGE_ACCESS_REASON = "android.settings.metadata.USAGE_ACCESS_REASON"
    const val ACTION_SECURITY_SETTINGS = "android.settings.SECURITY_SETTINGS"
    const val ACTION_MANAGE_UNKNOWN_APP_SOURCES = "android.settings.MANAGE_UNKNOWN_APP_SOURCES"
    const val ACTION_MANAGE_CROSS_PROFILE_ACCESS = "android.settings.MANAGE_CROSS_PROFILE_ACCESS"
    const val ACTION_APP_OPEN_BY_DEFAULT_SETTINGS = "com.android.settings.APP_OPEN_BY_DEFAULT_SETTINGS"

    const val ACTION_TRUSTED_CREDENTIALS_USER = "com.android.settings.TRUSTED_CREDENTIALS_USER"
    const val ACTION_MONITORING_CERT_INFO = "com.android.settings.MONITORING_CERT_INFO"
    const val ACTION_PRIVACY_SETTINGS = "android.settings.PRIVACY_SETTINGS"
    const val ACTION_VPN_SETTINGS = "android.settings.VPN_SETTINGS"
    const val ACTION_WIFI_SETTINGS = "android.settings.WIFI_SETTINGS"
    const val ACTION_WIFI_IP_SETTINGS = "android.settings.WIFI_IP_SETTINGS"
    const val ACTION_PROCESS_WIFI_EASY_CONNECT_URI = "android.settings.PROCESS_WIFI_EASY_CONNECT_URI"
    const val EXTRA_EASY_CONNECT_ERROR_CODE = "android.provider.extra.EASY_CONNECT_ERROR_CODE"
    const val EXTRA_EASY_CONNECT_ATTEMPTED_SSID = "android.provider.extra.EASY_CONNECT_ATTEMPTED_SSID"
    const val EXTRA_EASY_CONNECT_CHANNEL_LIST = "android.provider.extra.EASY_CONNECT_CHANNEL_LIST"
    const val EXTRA_EASY_CONNECT_BAND_LIST = "android.provider.extra.EASY_CONNECT_BAND_LIST"
    const val ACTION_DATA_USAGE_SETTINGS = "android.settings.DATA_USAGE_SETTINGS"
    const val ACTION_BLUETOOTH_SETTINGS = "android.settings.BLUETOOTH_SETTINGS"
    const val ACTION_APP_SEARCH_SETTINGS = "android.settings.APP_SEARCH_SETTINGS"
    const val ACTION_ASSIST_GESTURE_SETTINGS = "android.settings.ASSIST_GESTURE_SETTINGS"

    @Deprecated("")
    const val ACTION_FINGERPRINT_ENROLL = "android.settings.FINGERPRINT_ENROLL"
    const val ACTION_BIOMETRIC_ENROLL = "android.settings.BIOMETRIC_ENROLL"
    const val EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED = "android.provider.extra.BIOMETRIC_AUTHENTICATORS_ALLOWED"
    const val ACTION_CAST_SETTINGS = "android.settings.CAST_SETTINGS"
    const val ACTION_DATE_SETTINGS = "android.settings.DATE_SETTINGS"
    const val ACTION_SOUND_SETTINGS = "android.settings.SOUND_SETTINGS"
    const val ACTION_DISPLAY_SETTINGS = "android.settings.DISPLAY_SETTINGS"
    const val ACTION_NIGHT_DISPLAY_SETTINGS = "android.settings.NIGHT_DISPLAY_SETTINGS"
    const val ACTION_DARK_THEME_SETTINGS = "android.settings.DARK_THEME_SETTINGS"
    const val ACTION_LOCALE_SETTINGS = "android.settings.LOCALE_SETTINGS"
    const val ACTION_VOICE_INPUT_SETTINGS = "android.settings.VOICE_INPUT_SETTINGS"
    const val ACTION_INPUT_METHOD_SETTINGS = "android.settings.INPUT_METHOD_SETTINGS"
    const val ACTION_INPUT_METHOD_SUBTYPE_SETTINGS = "android.settings.INPUT_METHOD_SUBTYPE_SETTINGS"
    const val ACTION_USER_DICTIONARY_SETTINGS = "android.settings.USER_DICTIONARY_SETTINGS"
    const val ACTION_HARD_KEYBOARD_SETTINGS = "android.settings.HARD_KEYBOARD_SETTINGS"

    const val ACTION_USER_DICTIONARY_INSERT = "com.android.settings.USER_DICTIONARY_INSERT"
    const val ACTION_APPLICATION_SETTINGS = "android.settings.APPLICATION_SETTINGS"
    const val ACTION_APPLICATION_DEVELOPMENT_SETTINGS = "android.settings.APPLICATION_DEVELOPMENT_SETTINGS"
    const val ACTION_QUICK_LAUNCH_SETTINGS = "android.settings.QUICK_LAUNCH_SETTINGS"
    const val ACTION_MANAGE_APPLICATIONS_SETTINGS = "android.settings.MANAGE_APPLICATIONS_SETTINGS"
    const val ACTION_MANAGE_ALL_APPLICATIONS_SETTINGS = "android.settings.MANAGE_ALL_APPLICATIONS_SETTINGS"
    const val ACTION_MANAGE_OVERLAY_PERMISSION = "android.settings.action.MANAGE_OVERLAY_PERMISSION"

    const val ACTION_MANAGE_APP_OVERLAY_PERMISSION = "android.settings.MANAGE_APP_OVERLAY_PERMISSION"
    const val ACTION_MANAGE_WRITE_SETTINGS = "android.settings.action.MANAGE_WRITE_SETTINGS"
    const val ACTION_APP_USAGE_SETTINGS = "android.settings.action.APP_USAGE_SETTINGS"
    const val ACTION_APPLICATION_DETAILS_SETTINGS = "android.settings.APPLICATION_DETAILS_SETTINGS"
    const val ACTION_FOREGROUND_SERVICES_SETTINGS = "android.settings.FOREGROUND_SERVICES_SETTINGS"
    const val ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS = "android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS"
    const val ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS = "android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"
    const val ACTION_VIEW_ADVANCED_POWER_USAGE_DETAIL = "android.settings.VIEW_ADVANCED_POWER_USAGE_DETAIL"
    const val ACTION_IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS =
        "android.settings.IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS"
    const val ACTION_APP_OPS_SETTINGS = "android.settings.APP_OPS_SETTINGS"
    const val ACTION_SYSTEM_UPDATE_SETTINGS = "android.settings.SYSTEM_UPDATE_SETTINGS"
    const val ACTION_MANAGED_PROFILE_SETTINGS = "android.settings.MANAGED_PROFILE_SETTINGS"
    const val ACTION_SYNC_SETTINGS = "android.settings.SYNC_SETTINGS"
    const val ACTION_ADD_ACCOUNT = "android.settings.ADD_ACCOUNT_SETTINGS"
    const val ACTION_DATA_SAVER_SETTINGS = "android.settings.DATA_SAVER_SETTINGS"
    const val ACTION_NETWORK_OPERATOR_SETTINGS = "android.settings.NETWORK_OPERATOR_SETTINGS"
    const val ACTION_DATA_ROAMING_SETTINGS = "android.settings.DATA_ROAMING_SETTINGS"
    const val ACTION_INTERNAL_STORAGE_SETTINGS = "android.settings.INTERNAL_STORAGE_SETTINGS"
    const val ACTION_MEMORY_CARD_SETTINGS = "android.settings.MEMORY_CARD_SETTINGS"
    const val ACTION_SEARCH_SETTINGS = "android.search.action.SEARCH_SETTINGS"
    const val ACTION_DEVICE_INFO_SETTINGS = "android.settings.DEVICE_INFO_SETTINGS"
    const val ACTION_NFC_SETTINGS = "android.settings.NFC_SETTINGS"
    const val ACTION_NFCSHARING_SETTINGS = "android.settings.NFCSHARING_SETTINGS"
    const val ACTION_NFC_PAYMENT_SETTINGS = "android.settings.NFC_PAYMENT_SETTINGS"
    const val ACTION_DREAM_SETTINGS = "android.settings.DREAM_SETTINGS"
    const val ACTION_NOTIFICATION_ASSISTANT_SETTINGS = "android.settings.NOTIFICATION_ASSISTANT_SETTINGS"
    const val ACTION_NOTIFICATION_LISTENER_SETTINGS = "android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"
    const val ACTION_NOTIFICATION_LISTENER_DETAIL_SETTINGS = "android.settings.NOTIFICATION_LISTENER_DETAIL_SETTINGS"
    const val EXTRA_NOTIFICATION_LISTENER_COMPONENT_NAME = "android.provider.extra.NOTIFICATION_LISTENER_COMPONENT_NAME"
    const val ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS = "android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS"

    const val ACTION_NOTIFICATION_POLICY_ACCESS_DETAIL_SETTINGS =
        "android.settings.NOTIFICATION_POLICY_ACCESS_DETAIL_SETTINGS"
    const val ACTION_CONDITION_PROVIDER_SETTINGS = "android.settings.ACTION_CONDITION_PROVIDER_SETTINGS"
    const val ACTION_CAPTIONING_SETTINGS = "android.settings.CAPTIONING_SETTINGS"
    const val ACTION_PRINT_SETTINGS = "android.settings.ACTION_PRINT_SETTINGS"
    const val ACTION_ZEN_MODE_SETTINGS = "android.settings.ZEN_MODE_SETTINGS"
    const val ZEN_MODE_BLOCKED_EFFECTS_SETTINGS = "android.settings.ZEN_MODE_BLOCKED_EFFECTS_SETTINGS"
    const val ZEN_MODE_ONBOARDING = "android.settings.ZEN_MODE_ONBOARDING"
    const val ACTION_ZEN_MODE_PRIORITY_SETTINGS = "android.settings.ZEN_MODE_PRIORITY_SETTINGS"
    const val ACTION_ZEN_MODE_AUTOMATION_SETTINGS = "android.settings.ZEN_MODE_AUTOMATION_SETTINGS"
    const val ACTION_VOICE_CONTROL_DO_NOT_DISTURB_MODE = "android.settings.VOICE_CONTROL_DO_NOT_DISTURB_MODE"
    const val ACTION_ZEN_MODE_SCHEDULE_RULE_SETTINGS = "android.settings.ZEN_MODE_SCHEDULE_RULE_SETTINGS"
    const val ACTION_ZEN_MODE_EVENT_RULE_SETTINGS = "android.settings.ZEN_MODE_EVENT_RULE_SETTINGS"
    const val ACTION_ZEN_MODE_EXTERNAL_RULE_SETTINGS = "android.settings.ZEN_MODE_EXTERNAL_RULE_SETTINGS"
    const val ACTION_SHOW_REGULATORY_INFO = "android.settings.SHOW_REGULATORY_INFO"
    const val DEVICE_NAME_SETTINGS = "android.settings.DEVICE_NAME"
    const val ACTION_PAIRING_SETTINGS = "android.settings.PAIRING_SETTINGS"
    const val ACTION_BATTERY_SAVER_SETTINGS = "android.settings.BATTERY_SAVER_SETTINGS"
    const val ACTION_VOICE_CONTROL_BATTERY_SAVER_MODE = "android.settings.VOICE_CONTROL_BATTERY_SAVER_MODE"
    const val ACTION_HOME_SETTINGS = "android.settings.HOME_SETTINGS"
    const val ACTION_MANAGE_DEFAULT_APPS_SETTINGS = "android.settings.MANAGE_DEFAULT_APPS_SETTINGS"

    const val ACTION_MANAGE_MORE_DEFAULT_APPS_SETTINGS = "android.settings.MANAGE_MORE_DEFAULT_APPS_SETTINGS"
    const val ACTION_NOTIFICATION_SETTINGS = "android.settings.NOTIFICATION_SETTINGS"
    const val ACTION_CONVERSATION_SETTINGS = "android.settings.CONVERSATION_SETTINGS"
    const val ACTION_NOTIFICATION_HISTORY = "android.settings.NOTIFICATION_HISTORY"
    const val ACTION_ALL_APPS_NOTIFICATION_SETTINGS = "android.settings.ALL_APPS_NOTIFICATION_SETTINGS"
    const val ACTION_APP_NOTIFICATION_SETTINGS = "android.settings.APP_NOTIFICATION_SETTINGS"
    const val ACTION_CHANNEL_NOTIFICATION_SETTINGS = "android.settings.CHANNEL_NOTIFICATION_SETTINGS"
    const val ACTION_APP_NOTIFICATION_BUBBLE_SETTINGS = "android.settings.APP_NOTIFICATION_BUBBLE_SETTINGS"
    const val EXTRA_APP_PACKAGE = "android.provider.extra.APP_PACKAGE"
    const val EXTRA_CHANNEL_ID = "android.provider.extra.CHANNEL_ID"
    const val EXTRA_CONVERSATION_ID = "android.provider.extra.CONVERSATION_ID"
    const val ACTION_APP_NOTIFICATION_REDACTION = "android.settings.ACTION_APP_NOTIFICATION_REDACTION"

    const val EXTRA_APP_UID = "app_uid"
    const val ACTION_POWER_MENU_SETTINGS = "android.settings.ACTION_POWER_MENU_SETTINGS"
    const val ACTION_DEVICE_CONTROLS_SETTINGS = "android.settings.ACTION_DEVICE_CONTROLS_SETTINGS"
    const val ACTION_MEDIA_CONTROLS_SETTINGS = "android.settings.ACTION_MEDIA_CONTROLS_SETTINGS"

    const val ACTION_SHOW_ADMIN_SUPPORT_DETAILS = "android.settings.SHOW_ADMIN_SUPPORT_DETAILS"
    const val ACTION_SHOW_REMOTE_BUGREPORT_DIALOG = "android.settings.SHOW_REMOTE_BUGREPORT_DIALOG"
    const val ACTION_VR_LISTENER_SETTINGS = "android.settings.VR_LISTENER_SETTINGS"
    const val ACTION_PICTURE_IN_PICTURE_SETTINGS = "android.settings.PICTURE_IN_PICTURE_SETTINGS"
    const val ACTION_STORAGE_MANAGER_SETTINGS = "android.settings.STORAGE_MANAGER_SETTINGS"
    const val ACTION_WEBVIEW_SETTINGS = "android.settings.WEBVIEW_SETTINGS"

    const val ACTION_ENTERPRISE_PRIVACY_SETTINGS = "android.settings.ENTERPRISE_PRIVACY_SETTINGS"
    const val ACTION_SHOW_WORK_POLICY_INFO = "android.settings.SHOW_WORK_POLICY_INFO"
    const val ACTION_REQUEST_SET_AUTOFILL_SERVICE = "android.settings.REQUEST_SET_AUTOFILL_SERVICE"
    const val ACTION_QUICK_ACCESS_WALLET_SETTINGS = "android.settings.QUICK_ACCESS_WALLET_SETTINGS"

    @Deprecated("")
    const val ACTION_STORAGE_VOLUME_ACCESS_SETTINGS = "android.settings.STORAGE_VOLUME_ACCESS_SETTINGS"

    const val ACTION_REQUEST_ENABLE_CONTENT_CAPTURE = "android.settings.REQUEST_ENABLE_CONTENT_CAPTURE"

    const val ACTION_MANAGE_DOMAIN_URLS = "android.settings.MANAGE_DOMAIN_URLS"

    const val ACTION_TETHER_SETTINGS = "android.settings.TETHER_SETTINGS"
    const val ACTION_ENABLE_MMS_DATA_REQUEST = "android.settings.ENABLE_MMS_DATA_REQUEST"
    const val EXTRA_ENABLE_MMS_DATA_REQUEST_REASON = "android.settings.extra.ENABLE_MMS_DATA_REQUEST_REASON"
    const val ENABLE_MMS_DATA_REQUEST_REASON_INCOMING_MMS = 0
    const val ENABLE_MMS_DATA_REQUEST_REASON_OUTGOING_MMS = 1
    const val ACTION_MMS_MESSAGE_SETTING = "android.settings.MMS_MESSAGE_SETTING"
    const val CALL_METHOD_GET_SYSTEM = "GET_system"
    const val CALL_METHOD_GET_SECURE = "GET_secure"
    const val CALL_METHOD_GET_GLOBAL = "GET_global"
    const val CALL_METHOD_GET_CONFIG = "GET_config"
    const val CALL_METHOD_TRACK_GENERATION_KEY = "_track_generation"
    const val CALL_METHOD_GENERATION_INDEX_KEY = "_generation_index"
    const val CALL_METHOD_GENERATION_KEY = "_generation"
    const val CALL_METHOD_USER_KEY = "_user"
    const val CALL_METHOD_MAKE_DEFAULT_KEY = "_make_default"
    const val CALL_METHOD_RESET_MODE_KEY = "_reset_mode"
    const val CALL_METHOD_TAG_KEY = "_tag"
    const val CALL_METHOD_PREFIX_KEY = "_prefix"
    const val CALL_METHOD_MONITOR_CALLBACK_KEY = "_monitor_callback_key"
    const val CALL_METHOD_FLAGS_KEY = "_flags"
    const val CALL_METHOD_OVERRIDEABLE_BY_RESTORE_KEY = "_overrideable_by_restore"
    const val CALL_METHOD_PUT_SYSTEM = "PUT_system"
    const val CALL_METHOD_PUT_SECURE = "PUT_secure"
    const val CALL_METHOD_PUT_GLOBAL = "PUT_global"
    const val CALL_METHOD_PUT_CONFIG = "PUT_config"
    const val CALL_METHOD_SET_ALL_CONFIG = "SET_ALL_config"
    const val CALL_METHOD_DELETE_SYSTEM = "DELETE_system"
    const val CALL_METHOD_DELETE_SECURE = "DELETE_secure"
    const val CALL_METHOD_DELETE_GLOBAL = "DELETE_global"
    const val CALL_METHOD_DELETE_CONFIG = "DELETE_config"
    const val CALL_METHOD_RESET_SECURE = "RESET_secure"
    const val CALL_METHOD_RESET_GLOBAL = "RESET_global"
    const val CALL_METHOD_RESET_CONFIG = "RESET_config"
    const val CALL_METHOD_LIST_SYSTEM = "LIST_system"
    const val CALL_METHOD_LIST_SECURE = "LIST_secure"
    const val CALL_METHOD_LIST_GLOBAL = "LIST_global"
    const val CALL_METHOD_LIST_CONFIG = "LIST_config"
    const val CALL_METHOD_REGISTER_MONITOR_CALLBACK_CONFIG = "REGISTER_MONITOR_CALLBACK_config"
    const val EXTRA_MONITOR_CALLBACK_TYPE = "monitor_callback_type"
    const val EXTRA_ACCESS_CALLBACK = "access_callback"
    const val EXTRA_NAMESPACE_UPDATED_CALLBACK = "namespace_updated_callback"
    const val EXTRA_NAMESPACE = "namespace"
    const val EXTRA_CALLING_PACKAGE = "calling_package"
    const val EXTRA_AUTHORITIES = "authorities"
    const val EXTRA_ACCOUNT_TYPES = "account_types"
    const val EXTRA_INPUT_METHOD_ID = "input_method_id"
    const val EXTRA_INPUT_DEVICE_IDENTIFIER = "input_device_identifier"
    const val EXTRA_AIRPLANE_MODE_ENABLED = "airplane_mode_enabled"
    const val EXTRA_BATTERY_SAVER_MODE_ENABLED = "android.settings.extra.battery_saver_mode_enabled"
    const val EXTRA_DO_NOT_DISTURB_MODE_ENABLED = "android.settings.extra.do_not_disturb_mode_enabled"
    const val EXTRA_DO_NOT_DISTURB_MODE_MINUTES = "android.settings.extra.do_not_disturb_mode_minutes"

    const val RESET_MODE_PACKAGE_DEFAULTS = 1
    const val RESET_MODE_UNTRUSTED_DEFAULTS = 2
    const val RESET_MODE_UNTRUSTED_CHANGES = 3
    const val RESET_MODE_TRUSTED_DEFAULTS = 4
    const val EXTRA_NUMBER_OF_CERTIFICATES = "android.settings.extra.number_of_certificates"
    private const val JID_RESOURCE_PREFIX = "android"
    const val AUTHORITY = "settings"
    private const val TAG = "Settings"
    private const val LOCAL_LOGV = false
    private const val sInSystemServer = false
    const val ACTION_WIFI_ADD_NETWORKS = "android.settings.WIFI_ADD_NETWORKS"
    const val EXTRA_WIFI_NETWORK_LIST = "android.provider.extra.WIFI_NETWORK_LIST"
    const val EXTRA_WIFI_NETWORK_RESULT_LIST = "android.provider.extra.WIFI_NETWORK_RESULT_LIST"
    const val ADD_WIFI_RESULT_SUCCESS = 0
    const val ADD_WIFI_RESULT_ADD_OR_UPDATE_FAILED = 1
    const val ADD_WIFI_RESULT_ALREADY_EXISTS = 2

    const val ACTION_BUGREPORT_HANDLER_SETTINGS = "android.settings.BUGREPORT_HANDLER_SETTINGS"
    const val ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION = "android.settings.MANAGE_ALL_FILES_ACCESS_PERMISSION"
    const val ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION = "android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION"

}